(* generated by dune *)

(** @canonical Number_string_notation_plugin.G_number_string *)
module G_number_string = Number_string_notation_plugin__G_number_string

(** @canonical Number_string_notation_plugin.Number *)
module Number = Number_string_notation_plugin__Number

(** @canonical Number_string_notation_plugin.String_notation *)
module String_notation = Number_string_notation_plugin__String_notation
