(* DO NOT EDIT THIS FILE: automatically generated by ../configure *)
(* Exact command that generated this file: *)
(* _build/default/tools/configure/configure.exe -coqide no -with-doc no -prefix /home/jesse/hprop_set_1/UniMath *)

let coqlib = "/home/jesse/hprop_set_1/UniMath/lib/coq"
let configdir = "/home/jesse/hprop_set_1/UniMath/etc/xdg/coq"
let datadir = "/home/jesse/hprop_set_1/UniMath/share/coq"
let docdir = "/home/jesse/hprop_set_1/UniMath/share/doc"
let coqlibsuffix = "lib/coq"
let configdirsuffix = "etc/xdg/coq"
let datadirsuffix = "share/coq"
let docdirsuffix = "share/doc"
let ocamlfind = "/home/jesse/.opam/default/bin/ocamlfind"
let caml_flags = "-thread -rectypes -w -a+1..3-4+5..8-9+10..26-27+28..40-41-42+43-44-45+46..47-48+49..57-58+59..66-67-68+69-70   -safe-string -strict-sequence"
let version = "8.16.1"
let caml_version = "4.13.1"
let caml_version_nums = [4;13;1]
let arch = "Linux"
let arch_is_win32 = false
let exec_extension = ""
let gtk_platform = `X11
let has_natdynlink = true
let vo_version = 81601l
let browser = "firefox -remote \"OpenURL(%s,new-tab)\" || firefox %s &"
let wwwcoq = "http://coq.inria.fr/"
let wwwbugtracker = "http://coq.inria.fr/bugs/"
let wwwrefman = "http://coq.inria.fr/distrib/V8.16.1/refman/"
let wwwstdlib = "http://coq.inria.fr/distrib/V8.16.1/stdlib/"
let localwwwrefman = "file://home/jesse/hprop_set_1/UniMath/share/doc/html/refman"
let bytecode_compiler = true
type native_compiler = NativeOff | NativeOn of { ondemand : bool }
let native_compiler = NativeOn {ondemand=true}

let core_src_dirs = [
  "boot";
  "config";
  "lib";
  "clib";
  "kernel";
  "library";
  "engine";
  "pretyping";
  "interp";
  "gramlib";
  "parsing";
  "proofs";
  "tactics";
  "toplevel";
  "printing";
  "ide";
  "stm";
  "vernac";
]

let plugins_dirs = [
  "plugins/btauto";
  "plugins/cc";
  "plugins/derive";
  "plugins/extraction";
  "plugins/firstorder";
  "plugins/funind";
  "plugins/ltac";
  "plugins/ltac2";
  "plugins/micromega";
  "plugins/nsatz";
  "plugins/ring";
  "plugins/rtauto";
  "plugins/ssr";
  "plugins/ssrmatching";
  "plugins/syntax";
]

let all_src_dirs = core_src_dirs @ plugins_dirs
