(* generated by dune *)

(** @canonical Firstorder_plugin.Formula *)
module Formula = Firstorder_plugin__Formula

(** @canonical Firstorder_plugin.G_ground *)
module G_ground = Firstorder_plugin__G_ground

(** @canonical Firstorder_plugin.Ground *)
module Ground = Firstorder_plugin__Ground

(** @canonical Firstorder_plugin.Instances *)
module Instances = Firstorder_plugin__Instances

(** @canonical Firstorder_plugin.Rules *)
module Rules = Firstorder_plugin__Rules

(** @canonical Firstorder_plugin.Sequent *)
module Sequent = Firstorder_plugin__Sequent

(** @canonical Firstorder_plugin.Unify *)
module Unify = Firstorder_plugin__Unify
